### ISSUE TITLE
HTTP 401 when opening live stream

### ISSUE THREAD

**Issue by ratcashdev** [movieshark/MindiGo#1]
Thanks a lot for this plugin! While it does not work (yet), I trust it will get into a working state soon.
```
2020-10-25 18:49:44.638 T:3467665632   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc3 in position 92: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.mindigo/default.py", line 297, in <module>
                                                params.get("icon"),
                                              File "/home/osmc/.kodi/addons/plugin.video.mindigo/default.py", line 234, in translate_link
                                                % (response.status_code, response.content.encode("utf-8"))
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 92: ordinal not in range(128)
                                            -->End of Python script error report<--
```

and a second one, loosely related:
```
2020-10-25 18:49:37.227 T:3459272928   ERROR: CCurlFile::Stat - Failed: SSL peer certificate or SSH remote key was not OK(60) for https://static.mindigo.hu/channels/hetitv.png
2020-10-25 18:49:39.556 T:3476058336   ERROR: CCurlFile::Stat - Failed: SSL peer certificate or SSH remote key was not OK(60) for https://static.mindigo.hu/channels/hirtv.png

```

**Comment by ratcashdev** [comment]
@MrDini123  Tried to track this down.
 It fails when calling `translate_link` and calling the api:
`curl "https://api.mindigo.hu/api/v2/streams/live?content_id=56vplvge&language=hu&type=hls" -H "x-application-id: myAppId" -H "x-access-token: myToken" -H "Referer: https://tv.mindigo.hu/csatornak/m2-hd-16"`
which results in:

```
020-10-26 12:30:20.824 T:3586040032   ERROR: url: https://api.mindigo.hu/api/v2/streams/live?content_id=56vplvge&language=hu&type=hls
2020-10-26 12:30:20.824 T:3586040032   ERROR: Referer: https://tv.mindigo.hu/csatornak/m2-hd-16
2020-10-26 12:30:21.213 T:3586040032   ERROR: code: 401
2020-10-26 12:30:21.214 T:3586040032   ERROR: {u'errorCode': 10901, u'message': u'Unauthorized', u'code': 401, u'type': u'error', u'errorMessage': u'Hiba t\xf6rt\xe9nt'}
```

**Comment by MrDini123** [comment]
Hey,

Thanks for reporting. Unfortunately they bumped their API version so the entire addon requires a rewrite. There are also some channels that are missing from the old api and they stopped broadcasting on that version. That's why the 401s.

I will take a look as soon as I got some time.

**Comment by ratcashdev** [comment]
@MrDini123 see the related PR, please.

**Comment by MrDini123** [comment]
Thanks for the PR once again. I hereby apologise for the huge delays regarding this project, but I reviewed everything in action now. Seemingly everything works perfectly, I only had to push out a few minor modifications. However one big thing to change will be related to EPG. As I saw you are currently requesting it and then generate the channel list. For some awkward reason I only had the esport channel listed then. I took a look and it seems the EPG sometimes returns the state "PAST" for currently played streams as well. I am not sure why this happens, but the only fix in this case would be to iterate over the epg and pick the currently running shows I believe. That's the only thing missing and then we can push this to the repo, but I believe I could do that part.

Appreciate all your time and I merged your PR.

**Comment by ratcashdev** [comment]
No worries. However, since posting this I encountered some usability issues:
1. The videos, after starting, can't be stopped - they pop back up
2. While channels and programs can be put on Favorites, these will rarely play, since by the time one clicks on them the program will not be 'live'.

I think there was one other thing I can't remember now. So I guess this will need some more time. Frankly,  I don't even know what's the proper way of fixing these issues, unfortunately.

**Comment by Diniboy1123** [comment]
I have used the built in player btw and it seemed to work fine with all the streams. I can even stop them. So that shouldn't be an issue unless you can provide me a way to reproduce.

And indeed the favorite functions is tricky to do, frankly I don't even use it often. But if its an issue we could update the stream when they start the playback. I believe the slug stays the same so it will still play.
