### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by zsoltszasz** [movieshark/MindiGo#4]
Hi, 

This addon is not working for me. I made the installation from movieshark repo then I signed in successfully. After choosing a TV station I receive an error: 

2022-01-08 12:19:28.638 T:1565164416 ERROR: EXCEPTION Thrown
(PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.UnicodeDecodeError'>
Error Contents: 'ascii' codec can't decode byte Oxc3 in position
92: ordinal not in range(128)
Traceback (most recent call last):
File "/storage/.kodi/addons/plugin.video.mindigo/default.py",
line 297, in <module>
params.get("icon"),
File "/storage/.kodi/addons/plugin.video.mindigo/default.py",
line 234, in translate_link
% (response.status_code, response.content.encode("utf-8"))
UnicodeDecodeError: 'ascii' codec can't decode byte Oxc3 in
position 92: ordinal not in range(128)
-->End of Python script error report<--

My version is: LibreELEC 9.2 with Kodi 18.9. What to do?

**Comment by MrDini123** [comment]
A new version by ratcashdev has just been published to the repo which will hopefully fix your issue. Please try and see whether it fixes the issue you are having or not.
